image: "hseeberger/scala-sbt:8u222_1.3.2_2.12.10"

variables:
  SBT_OPTS: "-Dsbt.global.base=/sbt-cache/.sbtboot -Dsbt.boot.directory=/sbt-cache/.boot -Dsbt.ivy.home=/sbt-cache/.ivy"

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - sbt docker:publishLocal

deploy:
  stage: deploy
  script:
    - sbt clean coverage test coverageReport coverageOff doc
  artifacts:
    paths:
      - public
